name: crypto_tracker
description: A new Flutter project to to keep track the current cryptocurrency market values.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  # User for state management , routing
  get: ^4.6.5

  # Use for api calling (HTTP clint)
  dio: ^5.2.1+1

  # Use for responsive design for all screen
  flutter_screenutil: ^5.8.4

  # Use for cache image loading and image error_handling
  cached_network_image: ^3.2.3

  # Use for show price chart
  fl_chart: ^0.63.0

  # date formate
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  fonts:
    - family: SpaceMono
      fonts:
        - asset: fonts/SpaceMono-Bold.ttf
        - asset: fonts/SpaceMono-Regular.ttf

